default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: redit_development

test:
  <<: *default
  database: redit_test

production:
  <<: *default
  database: redit_production
